server:
  port: 8062

eureka:
  client:
#    registerWithEureka: false #telling the server not to register himself in the service registry
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0 #wait time for subsequent sync
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
      routes:
      - id: basic-service
        uri: lb://basic-service
        order: 8000
        predicates:
        - Path=/basic/**
        filters:
        - RewritePath=/basic/(?<path>.*), /$\{path}
        - AddRequestHeader=X-Request-Foo, Bar
        - StripPrefix=1

      - id: wcs-service
        uri: lb://wcs-service
        order: 9000
        predicates:
        - Path=/wcs/**
        filters:
        - RewritePath=/wcs/(?<path>.*), /$\{path}

      - id: wes-service
        uri: lb://wes-service
        order: 10000
        predicates:
        - Path=/wes/**
        filters:
        - RewritePath=/wes/(?<path>.*), /$\{path}