server:
  port: 8090

eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#      leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5