server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
      - id: basic-service
        uri: lb://basic-service
        order: 8000
        predicates:
        - Path=/v1/basic/**
#        filters:
#        - RewritePath=/v1/basic/(?<path>.*), /$\{path}
#          - AddRequestHeader=X-Request-Foo, Bar
#          - StripPrefix=1
      - id: wcs-service
        uri: lb://wcs-service
        order: 9000
        predicates:
        - Path=/v1/wcs/**
        filters:
        - RewritePath=/v1/wcs/(?<path>.*), /$\{path}
      - id: wes-service
        uri: lb://wes-service
        order: 10000
        predicates:
        - Path=/v1/ces/**
        filters:
        - RewritePath=/v1/ces/(?<path>.*), /$\{path}