server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    basic:
      path: /v1/basic/**
      serviceId: basic-service
    wes:
      path: /v1/wes/**
      serviceId: wes-service
    wcs:
      path: /v1/wcs/**
      serviceId: wcs-service